name: nwt_reading
description: Bible reading schedule of the New World Translation for Jehovah's Witnesses.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 6.0.0+60000

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.9
  uuid: ^3.0.7

dev_dependencies:
  collection: ^1.17.2
  custom_lint: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/repositories/
