name: nwt_reading
description: "Bible reading schedule of the New World  Translation for Jehovah's Witnesses."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 6.3.4+60304

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  collection: ^1.18.0
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  msix: ^3.16.8
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/whats_new/
    - assets/repositories/

msix_config:
  display_name: NWT Reading
  identity_name: 25845SearchWork.org.NWTReading
  publisher_display_name: Werner Fleischer
  languages: en, cs, de, es, fr, hu, it, nl, pl, pt, ro, ru
  output_name: NWT Reading
  logo_path: assets/launcher/icon.png
  trim_logo: false
  capabilities: internetClient
