name: nwt_reading
description: Bible reading schedule of the New World Translation for Jehovah's Witnesses.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  uuid: ^3.0.7

dev_dependencies:
  collection: ^1.16.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/repositories/
